name: Economy
main: xyz.minerune.economy.EconomyPlugin
version: "${pom.version}"
api: 1.0.13
authors:
  - "https://github.com/seetch"
website: "https://github.com/minerune/Economy"

permissions:
  economy.command.balance:
    default: true
  economy.command.pay:
    default: true
  economy.command.givemoney:
    default: op
  economy.command.setmoney:
    default: op
  economy.command.takemoney:
    default: op