name: Economy
version: "${pom.version}"
main: xyz.minerune.economy.Economy
api: 1.0.13
author: seetch
softdepend:
  - API
  - DataManager

permissions:
  economy.command.balance:
    default: true
  economy.command.pay:
    default: true
  economy.command.givemoney:
    default: op
  economy.command.setmoney:
    default: op
  economy.command.takemoney:
    default: op